paths:
  data_dir: /content/drive/MyDrive/tcc-modelo/data
  artifacts_dir: /content/drive/MyDrive/tcc-modelo/artifacts
  reports_dir: /content/drive/MyDrive/tcc-modelo/reports
datasets:
  olist:
    raw_dir: /content/drive/MyDrive/tcc-modelo/data/raw
    interim_dir: /content/drive/MyDrive/tcc-modelo/data/interim
    processed_dir: /content/drive/MyDrive/tcc-modelo/data/processed
timezone: America/Fortaleza
date_format: '%Y-%m-%d'
